# debug
debug: false

# database
database:
  host:
  name:
  username:
  password:

# server
server:
  port: 8080

# spring core
spring:
  profiles.active: dev
  datasource:
    username: ${database.username}
    password: ${database.password}
    url: jdbc:mysql://${database.host}:3306/${database.name}?characterEncoding=utf-8&useUnicode=true&useSSL=false&rewriteBatchedStatements=TRUE

  jpa:
    repositories.enabled: false
    database: MYSQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    properties.hibernate.enable_lazy_load_no_trans: true


  thymeleaf:
    enabled: true
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
    mode: LEGACYHTML5

  devtools.restart.exclude: static

# logging
logging:
  file: banana-king.log
  file.max-size: 500MB
  level.com.example.bananaking: error

facebook:
  version: v3.0
  base-url: https://graph.facebook.com/${facebook.version}/
  app:
  secret:
  access-token:

  page:
    id:
    name:
    token:
